# Generated by Django 5.1.4 on 2026-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stream_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageentry',
            name='storage_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
